# 2A assignment

<a href="https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/backpropagation.png">
![](https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/backpropagation.png)</a>

If you are building your own neural network, you will definitely need to understand how to train it. Backpropagation is a commonly used technique for training neural network. There are many resources explaining the technique, but this post will explain backpropagation with concrete example in a very detailed colorful steps.

## Overview

In this post, we will build a neural network with three layers:

- **Input** layer with two inputs neurons
- One **hidden** layer with two neurons 
- **Output** layer with a single neuron 

<a href="https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/nn1.png">
![](https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/nn1.png)
</a>

## Weights, weights, weights

Neural network training is about finding weights that minimize prediction error. We usually start our training with a set of randomly generated weights.Then, backpropagation is used to update the weights in an attempt to correctly map arbitrary inputs to outputs.

Our initial weights will be as following:
`w1 = 0.13`, `w2 = 0.22`, `w3 = 0.14`, `w4 = 0.09`, `w5 = 0.15` and `w6 = 0.16`

<a href="https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/bp_weights.png">
![](https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/bp_weights.png)
</a>

## Dataset

Our dataset has one sample with two inputs and one output. 

<a href="https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/bp_dataset.png">
![](https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/bp_dataset.png)
</a>

Our single sample is as following `inputs=[4, 5]` and `output=[2]`.

<a href="https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/bp_sample.png">
![](https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/bp_sample.png)
</a>

## Forward Pass

We will use given weights and inputs to predict the output. Inputs are multiplied by weights; the results are then passed forward to next layer. 

<a href="https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/bp_forward.png">
![](https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/bp_forward.png)
</a>

## Calculating Error

Now, it's time to find out how our network performed by calculating the difference between the actual output and predicted one. It's clear that our network output, or **prediction**, is not even close to **actual output**. We can calculate the difference or the error as following.

<a href="https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/bp_error.png">
![](https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/bp_error.png)
</a>

## Reducing Error

Our main goal of the training is to reduce the **error** or the difference between **prediction** and **actual output**. Since **actual output** is constant, "not changing", the only way to reduce the error is to change **prediction** value. The question now is, how to change **prediction** value?

By decomposing **prediction** into its basic elements we can find that **weights** are the variable elements affecting **prediction** value. In other words, in order to change **prediction** value, we need to change **weights** values. 

<a href="http://hmkcode.github.io/images/ai/bp_prediction_elements.png">
<img class="size-full wp-image-315 aligncenter" src="http://hmkcode.github.io/images/ai/bp_prediction_elements.png" alt="get-location"/>
</a>

> The question now is **how to change\update the weights value so that the error is reduced?**  
> The answer is **Backpropagation!**

## **Backpropagation**

**Backpropagation**,  short for "backward propagation of errors", is a mechanism used to update the **weights** using [gradient descent](https://en.wikipedia.org/wiki/Gradient_descent). It calculates the gradient of the error function with respect to the neural network's weights. The calculation proceeds backwards through the network.

> **Gradient descent** is an iterative optimization algorithm for finding the minimum of a function; in our case we want to minimize th error function. To find a local minimum of a function using gradient descent, one takes steps proportional to the negative of the gradient of the function at the current point. 

<a href="http://hmkcode.github.io/images/ai/bp_update_formula.png">
<img class="size-full wp-image-315 aligncenter" src="http://hmkcode.github.io/images/ai/bp_update_formula.png" alt="get-location"/>
</a>

For example, to update `w6`, we take the current `w6` and subtract the partial derivative of **error** function with respect to `w6`. Optionally, we multiply the derivative of the **error** function by a selected number to make sure that the new updated **weight** is minimizing the error function; this number is called ***learning rate***. 

<a href="http://hmkcode.github.io/images/ai/bp_w6_update.png">
<img class="size-full wp-image-315 aligncenter" src="http://hmkcode.github.io/images/ai/bp_w6_update.png" alt="get-location"/>
</a>

The derivation of the error function is evaluated by applying the chain rule as following

<a href="http://hmkcode.github.io/images/ai/bp_error_function_partial_derivative_w6.png">
<img class="size-full wp-image-315 aligncenter" src="http://hmkcode.github.io/images/ai/bp_error_function_partial_derivative_w6.png" alt="get-location"/>
</a>

So to update `w6` we can apply the following formula

<a href="http://hmkcode.github.io/images/ai/bp_w6_update_closed_form.png">
<img class="size-full wp-image-315 aligncenter" src="http://hmkcode.github.io/images/ai/bp_w6_update_closed_form.png" alt="get-location"/>
</a>

Similarly, we can derive the update formula for `w5` and any other weights existing between the output and the hidden layer.

<a href="http://hmkcode.github.io/images/ai/bp_w5_update_closed_form.png">
<img class="size-full wp-image-315 aligncenter" src="http://hmkcode.github.io/images/ai/bp_w5_update_closed_form.png" alt="get-location"/>
</a>

However, when moving backward to update `w1`, `w2`, `w3` and `w4` existing between input and hidden layer, the partial derivative for the error function with respect to `w1`, for example, will be as following.

<a href="http://hmkcode.github.io/images/ai/bp_error_function_partial_derivative_w1.png">
<img class="size-full wp-image-315 aligncenter" src="http://hmkcode.github.io/images/ai/bp_error_function_partial_derivative_w1.png" alt="get-location"/>
</a>

We can find the update formula for the remaining weights `w2`, `w3` and `w4` in the same way. 

In summary, the update formulas for all weights will be as following:

<a href="http://hmkcode.github.io/images/ai/bp_update_all_weights.png">
<img class="size-full wp-image-315 aligncenter" src="http://hmkcode.github.io/images/ai/bp_update_all_weights.png" alt="get-location"/>
</a>

We can rewrite the update formulas in matrices as following

<a href="http://hmkcode.github.io/images/ai/bp_update_all_weights_matrix.png">
<img class="size-full wp-image-315 aligncenter" src="http://hmkcode.github.io/images/ai/bp_update_all_weights_matrix.png" alt="get-location"/>
</a>

## Backward Pass

Using derived formulas we can find the new **weights**. 

> **Learning rate:** is a hyperparameter which means that we need to manually guess its value.

<a href="https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/bp_new_weights.png">
![](https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/bp_new_weights.png)
</a>

Now, using the new **weights** we will repeat the forward passed

<a href="https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/bp_forward_2.png">
![](https://raw.githubusercontent.com/amanpreetsingh459/EIP3_2019/master/Phase1/Session%202/Assignment/images/bp_forward_2.png)
</a>

We can notice that the **prediction** `0.76` is a little bit closer to **actual output** than the previously predicted one `0.404`. We can repeat the same process of backward and forward pass until **error** is close or equal to zero. In the below python exercise we have repeated the process for 10 times and got the predicted result as `1.99`. Cool!

# 2B assignment

In [119]:
import numpy as np
np.random.seed(3)

In [120]:
#Input array
X=np.array([[4,5]])

#Output
y=np.array([[2]])

In [121]:
print(X.shape)
print(y.shape)

(1, 2)
(1, 1)


In [122]:
#Variable initialization
epoch=10 #Setting training iterations
learning_rate=0.03 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 2 #number of 1st hidden layer's neurons
output_neurons = 1 #number of neurons at output layer

In [123]:
#Variable initialization
print("Epochs:",epoch)
print("Learning rate:", learning_rate)
print("Input layer neurons:",inputlayer_neurons)
print("Hidden layer neurons:",hiddenlayer_neurons)
print("Output neurons:",output_neurons)

Epochs: 10
Learning rate: 0.03
Input layer neurons: 2
Hidden layer neurons: 2
Output neurons: 1


In [124]:
#weight and bias initialization
weights_input_to_hidden = np.array([[.13, .14], [.22, .09]]) #np.random.normal(size=(inputlayer_neurons,hiddenlayer_neurons))

weights_hidden_to_output = np.array([[.15], [.16]]) #np.random.normal(size=(hiddenlayer_neurons,output_neurons))

In [125]:
print("weights_input_to_hidden:")
print(weights_input_to_hidden)
print("weights_hidden_to_output")
print(weights_hidden_to_output)
print("weights_input_to_hidden shape")
print(weights_input_to_hidden.shape)
print("weights_hidden_to_output shape")
print(weights_hidden_to_output.shape)

weights_input_to_hidden:
[[ 0.13  0.14]
 [ 0.22  0.09]]
weights_hidden_to_output
[[ 0.15]
 [ 0.16]]
weights_input_to_hidden shape
(2, 2)
weights_hidden_to_output shape
(2, 1)


In [126]:
for i in range(epoch):
    print("Epoch {0} ---------------------------------------------------------".format(i+1))
    #Forward Propogation
    hidden_layer_activations = np.dot(X, weights_input_to_hidden)
    print("Hidden layer output:")
    print(hidden_layer_activations)
    output_layer_activations = np.dot(hidden_layer_activations, weights_hidden_to_output)
    print("######Output layer output after epoch {0}:############".format(i+1))
    print(output_layer_activations)
    print("####################")
    
    error_output_layer = ((output_layer_activations - y)**2) / 2
    print("Error during first epoch")
    print(error_output_layer)
    
    delta = output_layer_activations - y
    print("delta from output layer:")
    print(delta)
        
    #update steps to update weights from hidden to output
    update_quantity = (learning_rate * delta).dot(hidden_layer_activations).T
    print("Quantity to be updated in the weights:")
    print(update_quantity)
        
    weights_hidden_to_output -= update_quantity
    print("Updated weights hidden to output layer:")
    print(weights_hidden_to_output)
        
    update_quantity = np.dot((learning_rate * delta * X).T, weights_hidden_to_output.T)
    print("Quantity to be updated in the weights:")
    print(update_quantity)
    
    #update steps to update weights from input to hidden
    weights_input_to_hidden -= update_quantity
    print("Updated weights from input to hidden layer:")
    print(weights_input_to_hidden)

Epoch 1 ---------------------------------------------------------
Hidden layer output:
[[ 1.62  1.01]]
######Output layer output after epoch 1:############
[[ 0.4046]]
####################
Error during first epoch
[[ 1.27265058]]
delta from output layer:
[[-1.5954]]
Quantity to be updated in the weights:
[[-0.07753644]
 [-0.04834062]]
Updated weights hidden to output layer:
[[ 0.22753644]
 [ 0.20834062]]
Quantity to be updated in the weights:
[[-0.0435614  -0.0398864 ]
 [-0.05445175 -0.04985799]]
Updated weights from input to hidden layer:
[[ 0.1735614   0.1798864 ]
 [ 0.27445175  0.13985799]]
Epoch 2 ---------------------------------------------------------
Hidden layer output:
[[ 2.06650431  1.41883555]]
######Output layer output after epoch 2:############
[[ 0.76580611]]
####################
Error during first epoch
[[ 0.76161728]]
delta from output layer:
[[-1.23419389]]
Quantity to be updated in the weights:
[[-0.07651401]
 [-0.05253354]]
Updated weights hidden to output layer:
[[

#### Actual output : 2
#### Below we can see that after every epoch predicted output is reaching closer to the actual output

In [ ]:
######Output layer output after epoch 1:############
[[ 0.4046]]
####################
######Output layer output after epoch 2:############
[[ 0.76580611]]
####################
######Output layer output after epoch 3:############
[[ 1.24211054]]
####################
######Output layer output after epoch 4:############
[[ 1.66925338]]
####################
######Output layer output after epoch 5:############
[[ 1.89860771]]
####################
######Output layer output after epoch 6:############
[[ 1.97494415]]
####################
######Output layer output after epoch 7:############
[[ 1.99426715]]
####################
######Output layer output after epoch 8:############
[[ 1.99871424]]
####################
######Output layer output after epoch 9:############
[[ 1.99971296]]
####################
######Output layer output after epoch 10:############
[[ 1.99993599]]
####################